version: '3.1'

services:
  # Database
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db1
    volumes: 
      - ./docker/db_only:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mysql_db_network

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql_db_network

  

networks:
  mysql_db_network:




# docker-compose -f docker-compose.local.db.yml up -d

# docker-compose -f docker-compose.local.db.yml up --build

# docker-compose -f docker-compose.local.db.yml down
